import Head from "next/head";

export default function Home() {
    return (
        <>
            <div>
                <Head>
                    <title>CRUD Application</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main>
                    <h1 className="text-xl md:text-5xl text-center font-bold py-10">
                        Employee Management
                    </h1>
                </main>
            </div>
        </>
    );
}
