import Form from "@/components/Form";
import Table from "@/components/Table";
import Head from "next/head";
import { BiUserPlus } from "react-icons/bi";

export default function Home() {
    return (
        <>
            <section>
                <Head>
                    <title>CRUD Application</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main className="py-5">
                    <h1 className="text-xl md:text-5xl text-center font-bold py-10">
                        Employee Management
                    </h1>

                    <div className="container mx-auto py-5 flex justify-between border-b">
                        <div className="left flex gap-3">
                            <button className="flex bg-indigo-500 text-white px-4 py-2 border rounded hover:bg-indigo-600 transition-transform active:scale-95">
                                Add Employee
                                <span className="pl-3">
                                    <BiUserPlus size={24} />
                                </span>
                            </button>
                        </div>
                    </div>
                </main>
                {/* Collapsable form start */}
                <div className="container mx-auto py-5">
                    <Form />
                </div>
                {/* Collapsable form end */}
                {/* Table start */}
                <div className="container mx-auto">
                    <Table />
                </div>
                {/* Table end */}
            </section>
        </>
    );
}
